name: Depdendency Check

on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
          
      - name: Java info
        run: |
          echo which java:
          which java
          echo java -versions
          java -version
          echo JAVA_HOME: $JAVA_HOME

      - name: Build project with Maven
        run: mvn clean install -DskipTests
        
      - name: Set JAVA_HOME for DC
        run: |
          export JAVA_HOME=/opt/jdk
          echo JAVA_HOME: $JAVA_HOME
      
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
            --enableRetired
    
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
